Updated azure commands to log error messages

diff --git a/.github/workflows/Backend.Deploy.yml b/.github/workflows/Backend.Deploy.yml
--- a/.github/workflows/Backend.Deploy.yml
+++ b/.github/workflows/Backend.Deploy.yml
@@ -55,7 +55,19 @@ jobs:
           docker buildx build --push --tag ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.BACKEND_NAME }}:latest --file ./src/Backend/Dockerfile .
       - name: Azure Login
         run: |
-          az login --output none --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}
+          OUTPUT=$(az login --output none --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "Failed to log in to Azure: $OUTPUT"
+            exit 1
+          else
+            echo "Logged in to Azure successfully"
+          fi
       - name: Deploy to Azure Container Apps
         run: |
-          az containerapp update --output none --name ${{ secrets.BACKEND_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.BACKEND_NAME }}:latest --replace-env-vars ASPNETCORE_ENVIRONMENT=Production FRONTEND_URL=https://${{ secrets.FRONTEND_NAME }}.${{ secrets.FRONTEND_SUBDOMAIN }}.${{ secrets.FRONTEND_REGION }}.azurecontainerapps.io DB_SERVER=${{ secrets.DB_SERVER_NAME }}.database.windows.net DB=${{ secrets.DB }} DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} JWT_SECRET=${{ secrets.JWT_SECRET }}
+          OUTPUT=$(az containerapp update --output none --name ${{ secrets.BACKEND_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.BACKEND_NAME }}:latest --replace-env-vars ASPNETCORE_ENVIRONMENT=Production FRONTEND_URL=https://${{ secrets.FRONTEND_NAME }}.${{ secrets.FRONTEND_SUBDOMAIN }}.${{ secrets.FRONTEND_REGION }}.azurecontainerapps.io DB_SERVER=${{ secrets.DB_SERVER_NAME }}.database.windows.net DB=${{ secrets.DB }} DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} JWT_SECRET=${{ secrets.JWT_SECRET }} 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "Failed to deploy container app: $OUTPUT"
+            exit 1
+          else
+            echo "Container app deployment successful"
+          fi
diff --git a/.github/workflows/Frontend.Deploy.yml b/.github/workflows/Frontend.Deploy.yml
--- a/.github/workflows/Frontend.Deploy.yml
+++ b/.github/workflows/Frontend.Deploy.yml
@@ -99,7 +99,19 @@ jobs:
           docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.FRONTEND_NAME }}:latest
       - name: Azure Login
         run: |
-          az login --output none --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}
+          OUTPUT=$(az login --output none --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "Failed to log in to Azure: $OUTPUT"
+            exit 1
+          else
+            echo "Logged in to Azure successfully"
+          fi
       - name: Deploy to Azure Container Apps
         run: |
-          az containerapp update --output none --name ${{ secrets.FRONTEND_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.FRONTEND_NAME }}:latest --replace-env-vars BACKEND_URL=https://${{ secrets.BACKEND_NAME }}.${{ secrets.BACKEND_SUBDOMAIN }}.${{ secrets.BACKEND_REGION }}.azurecontainerapps.io
+          ERROR_OUTPUT=$(az containerapp update --output none --name ${{ secrets.FRONTEND_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.FRONTEND_NAME }}:latest --replace-env-vars BACKEND_URL=https://${{ secrets.BACKEND_NAME }}.${{ secrets.BACKEND_SUBDOMAIN }}.${{ secrets.BACKEND_REGION }}.azurecontainerapps.io 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "Failed to deploy container app: $OUTPUT"
+            exit 1
+          else
+            echo "Container app deployment successful"
+          fi
